name: 'Terraform'

on: 
   push:
     branches: 
     - feature
   pull_request:


jobs:
  terrform:
    name: 'Terraform'
   
    runs-on: ubuntu-latest
    environment: dev

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4
     
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: install azure-cli
        run: |
         az --version
         terraform version
    
      - name: Log in with Azure
        run:
          az login --service-principal -u ${{ secrets.CLIENTID }} -p ${{ secrets.CLIENTSECRET }} --tenant ${{ secrets.TENANTID }}
        # uses: azure/login@v1
        # with:
        #   creds: '${{ secrets.AZURE_CREDENTIALS }}'
        # env: 
        #   creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: 'Terraform Format'   
        id: fmt
        run: terraform fmt
        working-directory: './Tf-code'
        continue-on-error: true

      - name: 'Terraform init'
        id: init
        working-directory: './Tf-code'
        env:
          AZURE_RM_CLIENT_ID: ${{ secrets.CLIENTID }}
          AZURE_RM_CLIENT_SECRET: ${{ secrets.CLIENTSECRET }}
          AZURE_RM_TENANT_ID: ${{ secrets.TENANTID }}
        run: terraform init

      - name: 'Terraform plan'
        id: plan
        run: terraform plan
        continue-on-error: false



      


    
