name: 'Terraform'

on: 
   push:
     branches: 
     - feature
   pull_request:

jobs:
  terrform:
    name: 'Terraform'
   
    runs-on: ubuntu-latest
    environment: dev

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4
     
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7
    
      - name: Az CLI login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CLIENTID }}
          tenant-id: ${{ secrets.TENANTID }}
          subscription-id: ${{ secrets.SUBSCRIPTIONID }}
          run: az login
          
      - name: 'Terraform Format'   
        id: fmt
        run: terraform fmt
        working-directory: './Tf-code'
        continue-on-error: true

      - name: 'Terraform init'
        id: init
        working-directory: './Tf-code'
        run: terraform init

      - name: 'Terraform plan'
        id: plan
        run: terraform plan
        continue-on-error: false



      


    
