name: 'Terraform'

on: 
   push:
     branches: 
     - feature
   pull_request:


jobs:
  terrform:
    name: 'Terraform'
   
    runs-on: ubuntu-latest
    environment: dev

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4
     
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: install azure-cli
        run: |
         az --version
         terraform version
    
      - name: Log in with Azure
        run:
          az login --service-principal -u ${{ secrets.ARM_CLIENT_ID }} -p ${{ secrets.ARM_CLIENT_SECRET }} --tenant ${{ secrets.TENANT_ID }}
        # uses: azure/login@v1
        # with:
        #   creds: '${{ secrets.AZURE_CREDENTIALS }}'
        # env: 
        #   creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: 'Terraform Format'   
        id: fmt
        run: terraform fmt
        working-directory: './Tf-code'
        continue-on-error: true

      - name: 'Terraform init'
        id: init
        working-directory: './Tf-code'
<<<<<<< HEAD
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRETt: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
=======
        env:
            TF_VAR_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
            TF_VAR_client_id: ${{ secrets.ARM_CLIENT_ID }}
            TF_VAR_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
            TF_VAR_tenant_id: ${{ secrets.ARM_TENANT_ID }}
>>>>>>> 91cf99a4c43c43f35fee45f53e553693cfc0ddb0
        run: terraform init

      - name: 'Terraform plan'
        id: plan
        run: terraform plan
        continue-on-error: false


      


    
