name: 'Terraform destroy'

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - feature
    # paths-ignore:
    #  - '!github-destroy.yml' 
 
 
jobs:
  terrform:
    name: 'Terraform destroy'
   
    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRETt: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    runs-on: ubuntu-latest
    environment: dev

    defaults:
      run:
        shell: bash
       

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: Authenticate using a Service Principal
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: 'Terraform init'
        run: terraform init
        id: init
        

      - name: 'Terraform plan'
        id: plan
        run: terraform plan -out=terraform.plan
        continue-on-error: false

      - name: Terraform destroy
        id: destroy
        run: terraform destroy -auto-approve
       